schema = 3
cachePackages = ["github.com/Azure/azure-sdk-for-go/sdk/azcore", "github.com/Azure/azure-sdk-for-go/sdk/azcore/cloud", "github.com/Azure/azure-sdk-for-go/sdk/azcore/log", "github.com/Azure/azure-sdk-for-go/sdk/azcore/policy", "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime", "github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming", "github.com/Azure/azure-sdk-for-go/sdk/azcore/to", "github.com/Azure/azure-sdk-for-go/sdk/azcore/tracing", "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/blob", "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/bloberror", "github.com/Azure/azure-sdk-for-go/sdk/storage/azblob/sas", "github.com/aymanbagabas/go-osc52/v2", "github.com/beorn7/perks/quantile", "github.com/cespare/xxhash/v2", "github.com/charmbracelet/bubbles/progress", "github.com/charmbracelet/bubbletea", "github.com/charmbracelet/colorprofile", "github.com/charmbracelet/harmonica", "github.com/charmbracelet/lipgloss", "github.com/charmbracelet/lipgloss/table", "github.com/charmbracelet/log", "github.com/charmbracelet/x/ansi", "github.com/charmbracelet/x/ansi/parser", "github.com/charmbracelet/x/cellbuf", "github.com/charmbracelet/x/term", "github.com/chmduquesne/rollinghash", "github.com/chmduquesne/rollinghash/buzhash32", "github.com/chmduquesne/rollinghash/rabinkarp64", "github.com/clipperhouse/displaywidth", "github.com/clipperhouse/stringish", "github.com/clipperhouse/uax29/v2/graphemes", "github.com/edsrzf/mmap-go", "github.com/go-logfmt/logfmt", "github.com/go-logr/logr", "github.com/go-logr/logr/funcr", "github.com/go-logr/stdr", "github.com/gofrs/flock", "github.com/google/uuid", "github.com/hashicorp/cronexpr", "github.com/klauspost/compress", "github.com/klauspost/compress/flate", "github.com/klauspost/compress/fse", "github.com/klauspost/compress/huff0", "github.com/klauspost/compress/s2", "github.com/klauspost/compress/zstd", "github.com/klauspost/cpuid/v2", "github.com/klauspost/pgzip", "github.com/klauspost/reedsolomon", "github.com/kopia/kopia/fs", "github.com/kopia/kopia/fs/ignorefs", "github.com/kopia/kopia/fs/localfs", "github.com/kopia/kopia/repo", "github.com/kopia/kopia/repo/blob", "github.com/kopia/kopia/repo/blob/beforeop", "github.com/kopia/kopia/repo/blob/filesystem", "github.com/kopia/kopia/repo/blob/logging", "github.com/kopia/kopia/repo/blob/readonly", "github.com/kopia/kopia/repo/blob/sharded", "github.com/kopia/kopia/repo/blob/storagemetrics", "github.com/kopia/kopia/repo/blob/throttling", "github.com/kopia/kopia/repo/compression", "github.com/kopia/kopia/repo/content", "github.com/kopia/kopia/repo/content/index", "github.com/kopia/kopia/repo/content/indexblob", "github.com/kopia/kopia/repo/ecc", "github.com/kopia/kopia/repo/encryption", "github.com/kopia/kopia/repo/format", "github.com/kopia/kopia/repo/hashing", "github.com/kopia/kopia/repo/logging", "github.com/kopia/kopia/repo/maintenance", "github.com/kopia/kopia/repo/maintenancestats", "github.com/kopia/kopia/repo/manifest", "github.com/kopia/kopia/repo/object", "github.com/kopia/kopia/repo/splitter", "github.com/kopia/kopia/snapshot", "github.com/kopia/kopia/snapshot/policy", "github.com/kopia/kopia/snapshot/restore", "github.com/kopia/kopia/snapshot/snapshotfs", "github.com/kopia/kopia/snapshot/upload", "github.com/lucasb-eyer/go-colorful", "github.com/mattn/go-isatty", "github.com/mattn/go-runewidth", "github.com/muesli/ansi", "github.com/muesli/ansi/compressor", "github.com/muesli/cancelreader", "github.com/muesli/termenv", "github.com/munnerz/goautoneg", "github.com/natefinch/atomic", "github.com/petar/GoLLRB/llrb", "github.com/pierrec/lz4", "github.com/pkg/errors", "github.com/prometheus/client_golang/prometheus", "github.com/prometheus/client_golang/prometheus/promauto", "github.com/prometheus/client_model/go", "github.com/prometheus/common/expfmt", "github.com/prometheus/common/model", "github.com/prometheus/procfs", "github.com/rivo/uniseg", "github.com/spf13/cobra", "github.com/spf13/pflag", "github.com/xo/terminfo", "github.com/zeebo/blake3", "go.opentelemetry.io/auto/sdk", "go.opentelemetry.io/otel", "go.opentelemetry.io/otel/attribute", "go.opentelemetry.io/otel/baggage", "go.opentelemetry.io/otel/codes", "go.opentelemetry.io/otel/metric", "go.opentelemetry.io/otel/metric/embedded", "go.opentelemetry.io/otel/propagation", "go.opentelemetry.io/otel/semconv/v1.37.0", "go.opentelemetry.io/otel/trace", "go.opentelemetry.io/otel/trace/embedded", "go.opentelemetry.io/otel/trace/noop", "go.uber.org/multierr", "go.uber.org/zap", "go.uber.org/zap/buffer", "go.uber.org/zap/zapcore", "go.yaml.in/yaml/v2", "golang.org/x/crypto/blake2b", "golang.org/x/crypto/blake2s", "golang.org/x/crypto/chacha20", "golang.org/x/crypto/chacha20poly1305", "golang.org/x/crypto/pbkdf2", "golang.org/x/crypto/scrypt", "golang.org/x/exp/constraints", "golang.org/x/net/http/httpguts", "golang.org/x/net/http2", "golang.org/x/net/http2/hpack", "golang.org/x/net/idna", "golang.org/x/net/trace", "golang.org/x/sync/errgroup", "golang.org/x/sys/cpu", "golang.org/x/sys/unix", "golang.org/x/text/secure/bidirule", "golang.org/x/text/transform", "golang.org/x/text/unicode/bidi", "golang.org/x/text/unicode/norm", "google.golang.org/genproto/googleapis/rpc/status", "google.golang.org/grpc", "google.golang.org/grpc/attributes", "google.golang.org/grpc/backoff", "google.golang.org/grpc/balancer", "google.golang.org/grpc/balancer/base", "google.golang.org/grpc/balancer/endpointsharding", "google.golang.org/grpc/balancer/grpclb/state", "google.golang.org/grpc/balancer/pickfirst", "google.golang.org/grpc/balancer/roundrobin", "google.golang.org/grpc/binarylog/grpc_binarylog_v1", "google.golang.org/grpc/channelz", "google.golang.org/grpc/codes", "google.golang.org/grpc/connectivity", "google.golang.org/grpc/credentials", "google.golang.org/grpc/credentials/insecure", "google.golang.org/grpc/encoding", "google.golang.org/grpc/encoding/proto", "google.golang.org/grpc/experimental/stats", "google.golang.org/grpc/grpclog", "google.golang.org/grpc/keepalive", "google.golang.org/grpc/mem", "google.golang.org/grpc/metadata", "google.golang.org/grpc/peer", "google.golang.org/grpc/resolver", "google.golang.org/grpc/resolver/dns", "google.golang.org/grpc/serviceconfig", "google.golang.org/grpc/stats", "google.golang.org/grpc/status", "google.golang.org/grpc/tap", "google.golang.org/protobuf/encoding/protodelim", "google.golang.org/protobuf/encoding/protojson", "google.golang.org/protobuf/encoding/prototext", "google.golang.org/protobuf/encoding/protowire", "google.golang.org/protobuf/proto", "google.golang.org/protobuf/protoadapt", "google.golang.org/protobuf/reflect/protoreflect", "google.golang.org/protobuf/reflect/protoregistry", "google.golang.org/protobuf/runtime/protoiface", "google.golang.org/protobuf/runtime/protoimpl", "google.golang.org/protobuf/types/known/anypb", "google.golang.org/protobuf/types/known/durationpb", "google.golang.org/protobuf/types/known/timestamppb"]

[mod]
  [mod."github.com/Azure/azure-sdk-for-go/sdk/azcore"]
    version = "v1.20.0"
    hash = "sha256-6tsc9Cpon5HnMM7SFGhxyMubTsLmsH2DsvAnPcUv6C8="
  [mod."github.com/Azure/azure-sdk-for-go/sdk/internal"]
    version = "v1.11.2"
    hash = "sha256-O4Vo6D/fus3Qhs/Te644+jh2LfiG5PpiMkW0YWIbLCs="
  [mod."github.com/Azure/azure-sdk-for-go/sdk/storage/azblob"]
    version = "v1.6.3"
    hash = "sha256-EXq4SUCGdOu1FudEz7yTmeWx75Eg9enAcIc6i2lvtpI="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/charmbracelet/bubbles"]
    version = "v0.21.0"
    hash = "sha256-cfjUHgy9eq5SretTHuYuRaeeT6QmJYQBB9dsI8QSnW0="
  [mod."github.com/charmbracelet/bubbletea"]
    version = "v1.3.10"
    hash = "sha256-7wr85TLszu1CHNEMv+o4w+r24Z0xdzCgecPv+ZtRX/A="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.3.3"
    hash = "sha256-OIbahp2GyekOAHw7RB7/4WEOEjqpP/PqK6wfIq1iSkk="
  [mod."github.com/charmbracelet/harmonica"]
    version = "v0.2.0"
    hash = "sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v1.1.0"
    hash = "sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4="
  [mod."github.com/charmbracelet/log"]
    version = "v0.4.2"
    hash = "sha256-3w1PCM/c4JvVEh2d0sMfv4C77Xs1bPa1Ea84zdynC7I="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.10.3"
    hash = "sha256-bSv0OAESuOuXXUIWHLvR/VBnk2gbogSGhDsFDLyDObw="
  [mod."github.com/charmbracelet/x/cellbuf"]
    version = "v0.0.13-0.20250311204145-2c3ea96c31dd"
    hash = "sha256-XAhCOt8qJ2vR77lH1ez0IVU1/2CaLTq9jSmrHVg5HHU="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.2"
    hash = "sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4="
  [mod."github.com/chmduquesne/rollinghash"]
    version = "v4.0.0+incompatible"
    hash = "sha256-5TAGwWBRPFitrQGJRQpYK3Vx13X+FaPrGRveslNebjI="
  [mod."github.com/clipperhouse/displaywidth"]
    version = "v0.4.1"
    hash = "sha256-Cchc3GXYSn4eVbsY4DdqeCL0KAh1mYS/mMQnAzeVSBw="
  [mod."github.com/clipperhouse/stringish"]
    version = "v0.1.1"
    hash = "sha256-Mp8M1CRbwr6dcJ4BD9tXD5I78ZgCFEm0GDxJv0GYReg="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.3.0"
    hash = "sha256-dLL70mEOxrmYVoQjy2K7QvZiahAlJKOcFDz2mW/R/Do="
  [mod."github.com/edsrzf/mmap-go"]
    version = "v1.2.0"
    hash = "sha256-6iTbYkyZTJyNU+xZdqJT+mQ8O6Nk/W+0y5eNUTsX27M="
  [mod."github.com/erikgeiser/coninput"]
    version = "v0.0.0-20211004153227-1c3628e74d0f"
    hash = "sha256-OWSqN1+IoL73rWXWdbbcahZu8n2al90Y3eT5Z0vgHvU="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.1"
    hash = "sha256-+gUGmdR/QOsB9qKESLrsbq6tK2VssNT/kDbRFpgrZL4="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/gofrs/flock"]
    version = "v0.13.0"
    hash = "sha256-5imm90Iqstu+PnSX9RLZMHUG7qW2KX2t3xIpZ2cXSco="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/hashicorp/cronexpr"]
    version = "v1.1.3"
    hash = "sha256-MqpqvGiQbpg0E7xn3DJQ7YEo6vZQC1e5zuuyLecsOkE="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.2"
    hash = "sha256-mRa+6qEi5joqQao13ZFogmq67rOQzHCVbCCjKA+HKEc="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.3.0"
    hash = "sha256-50JhbQyT67BK38HIdJihPtjV7orYp96HknI2VP7A9Yc="
  [mod."github.com/klauspost/pgzip"]
    version = "v1.2.6"
    hash = "sha256-qA1hjnVW/tqxY48JIWQVulwEwY7fwyvnasymZk3mScg="
  [mod."github.com/klauspost/reedsolomon"]
    version = "v1.12.6"
    hash = "sha256-JOhqh5Wg36pg8KNWmenvdwr6eerXKoDGCne2dluFZAE="
  [mod."github.com/kopia/kopia"]
    version = "v0.22.3"
    hash = "sha256-GUXdSRuZ4+dh6O7nBYSP4z18RU5vopFdZSZDPUxB2NY="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.3.0"
    hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-localereader"]
    version = "v0.0.1"
    hash = "sha256-JlWckeGaWG+bXK8l8WEdZqmSiTwCA8b1qbmBKa/Fj3E="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.19"
    hash = "sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE="
  [mod."github.com/muesli/ansi"]
    version = "v0.0.0-20230316100256-276c6243b2f6"
    hash = "sha256-qRKn0Bh2yvP0QxeEMeZe11Vz0BPFIkVcleKsPeybKMs="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/termenv"]
    version = "v0.16.0"
    hash = "sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/mxk/go-vss"]
    version = "v1.2.0"
    hash = "sha256-lHj+E8E3ZkXXkNpfhedNOPMmfnI9qe1unnjhNAwBW5M="
  [mod."github.com/natefinch/atomic"]
    version = "v1.0.1"
    hash = "sha256-fbOVHCwRNI8PFjC4o0YXpKZO0JU2aWTfH5c7WXXKMHg="
  [mod."github.com/petar/GoLLRB"]
    version = "v0.0.0-20210522233825-ae3b015fd3e9"
    hash = "sha256-FkhvH+ogM8nTHyHwiRrQtrM70Xwp+1vhu9zdMyXaoEw="
  [mod."github.com/pierrec/lz4"]
    version = "v2.6.1+incompatible"
    hash = "sha256-5+4i5SN97wG71knAF9eUgEEG5k03HW4wPnAdPd6JSfE="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.23.2"
    hash = "sha256-3GD4fBFa1tJu8MS4TNP6r2re2eViUE+kWUaieIOQXCg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.2"
    hash = "sha256-q6Fh6v8iNJN9ypD47LjWmx66YITa3FyRjZMRsuRTFeQ="
  [mod."github.com/prometheus/common"]
    version = "v0.67.4"
    hash = "sha256-CFkwP3fePnBhXZelj7JcLYc0RT192t9ZkunWEAGEC1A="
  [mod."github.com/prometheus/procfs"]
    version = "v0.17.0"
    hash = "sha256-l9fVln5n1kmyoNKhHx69X9uzP0XYqnl1PEjHb7lOdzM="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."github.com/zeebo/blake3"]
    version = "v0.2.4"
    hash = "sha256-Q8KSVhnSR1cwfTp4LkPdfI1UWWkDDHa9fslNsa3Qfo8="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.2.1"
    hash = "sha256-73bFYhnxNf4SfeQ52ebnwOWywdQbqc9lWawCcSgofvE="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.38.0"
    hash = "sha256-OU4EVEGwbopbYZLDBfAelR/4yjzfV+UVp4UFt3UvkOE="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.38.0"
    hash = "sha256-5W6Yd9nl/eyvL29e9hSfosISpxfSQcBAwkqI4htHWCg="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.38.0"
    hash = "sha256-gNXUPmsPAw6JVH3YT/xwmRpn5QoDxyzc9kLe/5ldo0o="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.1"
    hash = "sha256-bn/MMu7X3GkUuW12Xwn9JYbOJeEu9+yoQtkmO+36xlQ="
  [mod."go.yaml.in/yaml/v2"]
    version = "v2.4.3"
    hash = "sha256-WqfrOUQFvfuORgl1yyVOcsEXU/vwWQHkcVWx3vCxvaw="
  [mod."golang.org/x/crypto"]
    version = "v0.45.0"
    hash = "sha256-IpNesJYxFcs2jGvagwJrUD/gsJfA3UiETjQwYByXxSY="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20251023183803-a4bb9ffd2546"
    hash = "sha256-y0/A9UdtYNDlFglHQ7TW8ixSR2G36wHMRNc3sL7JXBY="
  [mod."golang.org/x/net"]
    version = "v0.47.0"
    hash = "sha256-2qFgCd0YfNCGkLrf+xvnhQtKjSe8CymMdLlN3svUYTg="
  [mod."golang.org/x/sync"]
    version = "v0.18.0"
    hash = "sha256-S8o6y7GOaYWeq+TzT8BB6T+1mg82Mu08V0TL3ukJprg="
  [mod."golang.org/x/sys"]
    version = "v0.38.0"
    hash = "sha256-1+i5EaG3JwH3KMtefzJLG5R6jbOeJM4GK3/LHBVnSy0="
  [mod."golang.org/x/text"]
    version = "v0.31.0"
    hash = "sha256-AT46RrSmV6+/d5FDhs9fPwYzmQ7WSo+YL9tPfhREwLw="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20251103181224-f26f9409b101"
    hash = "sha256-I3ZNpNjKKvTq4DVNw3wLKrCuORabZ0oYj0KKhOMI/MA="
  [mod."google.golang.org/grpc"]
    version = "v1.77.0"
    hash = "sha256-RDkejy1CQ9em+6Pm0oWevEiWbzHSFo1QNut5uWH9TLE="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.10"
    hash = "sha256-gUrj1qSpjcpRKCBnrYlKMm+P0OSh7B/8EBREstwhD1w="
