# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """

$username$hostname$kubernetes$git_branch$git_commit$git_state$git_metrics$git_status
$all
"""

[kubernetes]
format = '[$symbol$context:$namespace](blue) '
symbol = "âš“"
disabled = false
contexts = [
  { context_pattern = "admin@talos-plexuz", style = "green", symbol = "âš“ ", context_alias = "talos" },
]

[cmd_duration]
format = "took [$duration]($style) "
style = "yellow bold"
show_notifications = false
min_time_to_notify = 45000

[username]
style_user = 'green bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold orange) '
disabled = false


[jobs]
symbol = "î¢ "
format = "[$number$symbol]($style) "
style  = "bold blue" 

[sudo]
symbol = "ğŸ’€ "
disabled = false

[container]
disabled = true

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch(:$remote_branch)]($style) "
